export const AUTH_LOGIN = 'AUTH_LOGIN'
export const FETXH_ALL_TASKLIST = 'FETXH_ALL_TASKLIST'
export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
